spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-security-jwt?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    #    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
  mvc:
    hiddenmethod:
      filter:
        enabled: 'true'
  sql:
    init:
      mode: never
#            mode: always
logging:
  level:
    #      org.hibernate.orm.jdbc.bind: trace
    org.hibernate.type: trace
    #      org.hibernate.stat: debug
    org.hibernate:sql: debug
#      org.hibernate.type.descriptor.sql.BasicBinder: trace

application:
  security:
    jwt:
      secret-key: 8bca91a0afcc4c59f0e1c0ceadc8a9f603122bb6b497ec5f3eeb2ca6273ed5b5
      expiration: 86400000 # one day
      refresh-token:
        expiration: 604800000 # seven days